# Setup
title:               InsomniacVegan
tagline:             ''
description:         'Personal blog of a part-time physicist, full time annoyance.'
url:                 https://insomniacvegan.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Luke E.
  url:               https://twitter.com/insomniacvegan
  email:             luke@insomniacvegan

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
